clear
clc
PlotSin=['Num=get(hs, ''Value'');'...
    'Set(heNum,''String'',num2str(Num));'...
    'Subplot(ha);'...
    'x=0:0.1:Num*pi;'...
    'plot(x,sin(x));'...
    'axis([0 Num*pi -1 1]);'...
    'xlabel(''x'')']